# Generated by Django 4.1.7 on 2023-03-15 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
